### ISSUE TITLE
sinon was updated, though only <7.0.0 version can be used

### ISSUE THREAD

**Issue by lutr01** [glacejs/glace-core#266]
I have noticed, that the functions of the glace-core are not executable, and I think the issue is that sinon version was updated till >7.0.0
though npm ERR! peer dep missing: sinon@>=4.0.0 <7.0.0, required by sinon-chai@3.2.0
error shows it should be less.

**Comment by schipiga** [comment]
@lutr01 thank you for report. Could you please provide, what functions are not working after installation? Or it's not possible to install `glace-core`?

It's strange to see, that it throws the `npm ERR` for you, cause in my case it just shows a warning: `npm WARN sinon-chai@3.2.0 requires a peer of sinon@>=4.0.0 <7.0.0 but none was installed.` about incompatible versions of used `sinon-chai` & `sinon`.

Could you please provide details, which operating system do you use & which command to install `glace-core` ?

**Comment by lutr01** [comment]
Hey!!!  Thank you for replying :)

I am not at my pc now and cannot provide details ! Will be tomorrow!

But in short what I remember, I installed core globally ! And ran the test
from your example for the glacejs where we tried to open Yandex.ru. And I
got error- openUrl is not a function or such .

Or cannot read access of undefined.

Such errors I was getting
. But again ,now cannot really provide full details :) though will now open
my home pc and try it here! Will let you know shortly if I get same errors

BR, Lu

**Comment by schipiga** [comment]
@lutr01 thank you for info. I think, `openUrl` wasn't found for you, maybe because you didn't use CLI option `--web`. Any case it needs to see a full stack trace of error, in order to say something concrete.

**Comment by lutr01** [comment]
hey Sergei, I am back.

I am running:

"use strict";

test("It should launch browser and open web page", () => {
    const url = "https://www.ya.ru";

    chunk(`Open url "${url}"`, async () => {
        await $.openUrl(url);
    });
});

and getting:

suite: Session 1/1/2019, 10:12:03 PM

  test: It should launch browser and open web page
    × chunk: Open url "https://www.ya.ru"

  × 1 failed test
  1 executed chunk

  Summary tests time is 0.033 sec

TEST FAILURES:

test: It should launch browser and open web page

Open url "https://www.ya.ru"
message: $.openUrl is not a function
stack: TypeError: $.openUrl is not a function
    at chunk (tests.js:7:17)
    at Context.<anonymous>
(C:\Users\lubov\AppData\Roaming\npm\node_modules\glace-core\lib\globals\chunk.js:118:18)
    at next
(C:\Users\lubov\AppData\Roaming\npm\node_modules\glace-core\lib\hacking.js:45:20)
    at Immediate.<anonymous>
(C:\Users\lubov\AppData\Roaming\npm\node_modules\glace-core\lib\hacking.js:88:9)


and when I am running your example:

from the glaceJs folder, example, I get the other error, with the undefuned
open Url.




чт, 3 янв. 2019 г. в 21:48, Lubova Tretjakova <lubova.tretjakova@gmail.com>:

**Comment by lutr01** [comment]
--web I used, and same result.

чт, 3 янв. 2019 г. в 22:06, Lubova Tretjakova <lubova.tretjakova@gmail.com>:

**Comment by schipiga** [comment]
@lutr01 ok, please share me a command which you use to launch your test.

**Comment by lutr01** [comment]
I run the command using power shell opened from the containing folder:
Glace tests.js —web

**Comment by schipiga** [comment]
@lutr01 ok, thank you, and pls share a command, how did you install it.

**Comment by lutr01** [comment]
Tomorrow at work I will fully describe the steps!

And thank you for the support !!!

**Comment by schipiga** [comment]
ok, thank you, and my hypothesis, that you use `glace` from `glace-core`, not from `glace-js`. They both add cli command `glace` to launch tests. But `glace` from `glace-core` can't manage web options and provide only basic functionality. On other side `glace` from `glace-js` can launch web tests. It's easy to understand which version do you use, calling its help for example: `glace -h`.

If you didn't see the same options list as in the page https://glacejs.github.io/glace-js/#toc4__anchor (and `--web` option as well), it means you use `glace-core`. And then you need to remove it and install `glace-js`.

**Comment by schipiga** [comment]
hey @lutr01 , any updates?

**Comment by lutr01** [comment]
Hey Sergei :)

I was in contact with Igor, who also was having a discussion with you! And
I realised, I was calling the test directly from project, not from the node
module.

I managed to make it work!

But now I have more questions-

1. Is it possible to test the DB with your framework? The state change,
triggers etc.
2. can I test API with your framework ?
3. If not, which frameworks would you recommend ?

Also could you please send me the example of real life tests project using
your framework?

Thanks, Lu

пт, 4 янв. 2019 г. в 12:50, Sergei Chipiga <notifications@github.com>:

**Comment by schipiga** [comment]
Hey @lutr01, thank you for response.

With `glacejs` you also can test db or api. But as with any other testing framework you should develop a code specific for you tests, like database connection, api requests, etc. And there are a lot good nodejs libraries for that, which can be used inside glacejs.
So here I don't see real profit from `glacejs` before `mochajs` or `jasminejs` or other nodejs testing framework. Of course it gives some candies like interactive mode, retry, relaunch failed tests only, fixtures and so on. Other frameworks also have other features too.
About UI testing with selenium I also recommend to try `codeceptjs`.
And about real examples, currently `glacejs` isn't used to test any open-source projects, where you can see real-world production tests. But you can glance to `e2e` tests which is used for `glacejs` self-testing:
- https://github.com/glacejs/glace-js/tree/master/tests/e2e
- https://github.com/glacejs/glace-js/blob/master/tests/e2e.steps.yaml - config to generate tests automatically from steps, using `glace-tesgen` plugin.
